### PR TITLE
fix(gateway): caller is not aware of the sent txId

### PR DESCRIPTION
**Pull request by dan-ziv**
### Description of the Changes

Issue: https://github.com/starkware-industries/starkex-clientlib-js/issues/9

Solution:
Return the used txId in the response body, so the client can trace its status.

### Check List

- [x] Changes have been done against master branch, and PR does not conflict
- [ ] New unit / functional tests have been added (whenever applicable)
- [ ] Test are passing in local environment
- [ ] Docs have been updated
- [ ] PR title is follow the convention: `<type>[optional scope]: <description>`, e.g: `fix: minor typos in code`

---
This change is [Reviewable](https://reviewable.io/reviews/starkware-industries/starkex-clientlib-js/10)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 2 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-industries/starkex-clientlib-js/10)* status: 2 of 6 files reviewed, 1 unresolved discussion (waiting on @dan-ziv and @lior-stark)

___
*[src/lib/gateway/gateway.ts, line 109 at r1](https://reviewable.io/reviews/starkware-industries/starkex-clientlib-js/10#-MocS6jj7bNVTrS_vxSf:-MocS6jk3OPw947-wijN:b-llrc38) ([raw file](https://github.com/starkware-industries/starkex-clientlib-js/blob/f9b3bec7c6d230726e23493e687a4107d69dd7b2/src/lib/gateway/gateway.ts#L109)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>       return {
>         txId,
>         ...response
>       };
> ```
</details>

Maybe:
```
return {
    txId,
    nativeResponse: response
};
```
?

**Review by dorimedini-starkware — COMMENTED** [review]
I reviewed the files I think I understand..

> *[Reviewable](https://reviewable.io/reviews/starkware-industries/starkex-clientlib-js/10#-:-MocSO6n6510O8tb56aB:bgphzb3)* status: 2 of 6 files reviewed, 1 unresolved discussion (waiting on @dan-ziv and @lior-stark)

**Comment by dan-ziv** [comment]
___
*[src/lib/gateway/gateway.ts, line 109 at r1](https://reviewable.io/reviews/starkware-industries/starkex-clientlib-js/10#-MocS6jj7bNVTrS_vxSf:-MocWGKMDX0lf3uzCb91:b-igt6om) ([raw file](https://github.com/starkware-industries/starkex-clientlib-js/blob/f9b3bec7c6d230726e23493e687a4107d69dd7b2/src/lib/gateway/gateway.ts#L109)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

> ```
>       return {
>         txId,
>         ...response
>       };
> ```
Maybe:
```
return {
    txId,
    nativeResponse: response
};
```
?
</blockquote></details>

Besides it will break those who use it right now, I less like it since it adds another nesting to the object.
In addition, it will add differentially to those APIs that you should refer `nativeResponse` to access the BE response.
@lior-stark WDYT?

**Review by lior-stark — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-industries/starkex-clientlib-js/10)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-ziv and @dorimedini-starkware)

___
*[src/lib/gateway/gateway.ts, line 109 at r1](https://reviewable.io/reviews/starkware-industries/starkex-clientlib-js/10#-MocS6jj7bNVTrS_vxSf:-Mocr5wA3PvMkO6tRXZB:b-gkvovz) ([raw file](https://github.com/starkware-industries/starkex-clientlib-js/blob/f9b3bec7c6d230726e23493e687a4107d69dd7b2/src/lib/gateway/gateway.ts#L109)):*
<details><summary><i>Previously, dan-ziv (Dan Ziv) wrote…</i></summary><blockquote>

Besides it will break those who use it right now, I less like it since it adds another nesting to the object.
In addition, it will add differentially to those APIs that you should refer `nativeResponse` to access the BE response.
@lior-stark WDYT?
</blockquote></details>

I tend to agree. 
Is there value in distinguishing between the txId and the response?
___
*[src/lib/gateway/gateway.ts, line 114 at r1](https://reviewable.io/reviews/starkware-industries/starkex-clientlib-js/10#-MocsFDtCIuekzLzyAeQ:-MocsFDtCIuekzLzyAeR:bfhhtsi) ([raw file](https://github.com/starkware-industries/starkex-clientlib-js/blob/f9b3bec7c6d230726e23493e687a4107d69dd7b2/src/lib/gateway/gateway.ts#L114)):*
> ```XML
>     } catch (err) {
>       //TODO: error handling
>       return Promise.reject(err);
> ```

you don't want to include the txn id in the response in case of errors?

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-industries/starkex-clientlib-js/10)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-ziv and @lior-stark)

___
*[src/lib/gateway/gateway.ts, line 109 at r1](https://reviewable.io/reviews/starkware-industries/starkex-clientlib-js/10#-MocS6jj7bNVTrS_vxSf:-Mod-WS68oaMPBkRrOB9:b-3uzuyq) ([raw file](https://github.com/starkware-industries/starkex-clientlib-js/blob/f9b3bec7c6d230726e23493e687a4107d69dd7b2/src/lib/gateway/gateway.ts#L109)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

I tend to agree. 
Is there value in distinguishing between the txId and the response?
</blockquote></details>

For those who want to use the playground to integrate their system to starkex, I think they should somehow be aware that the txId is not part of the 'usual' response. With `nativeResponse` at least they have another required indirection, so if they are unaware of this difference their script just won't run.
This is non-blocking though, whatever you decide.

**Comment by lior-stark** [comment]
___
*[src/lib/gateway/gateway.ts, line 109 at r1](https://reviewable.io/reviews/starkware-industries/starkex-clientlib-js/10#-MocS6jj7bNVTrS_vxSf:-Mom0uCP3W5meyokS34X:b2ju8o7) ([raw file](https://github.com/starkware-industries/starkex-clientlib-js/blob/f9b3bec7c6d230726e23493e687a4107d69dd7b2/src/lib/gateway/gateway.ts#L109)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

For those who want to use the playground to integrate their system to starkex, I think they should somehow be aware that the txId is not part of the 'usual' response. With `nativeResponse` at least they have another required indirection, so if they are unaware of this difference their script just won't run.
This is non-blocking though, whatever you decide.
</blockquote></details>

just out of curiosity, why is it not part of the "usual response"?
you mean the txId is some kind of metadata, and the response is the real data?

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-industries/starkex-clientlib-js/10)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-ziv)

___
*[src/lib/gateway/gateway.ts, line 109 at r1](https://reviewable.io/reviews/starkware-industries/starkex-clientlib-js/10#-MocS6jj7bNVTrS_vxSf:-MomGjuJ1koqy3wzKApU:bc8tohf) ([raw file](https://github.com/starkware-industries/starkex-clientlib-js/blob/f9b3bec7c6d230726e23493e687a4107d69dd7b2/src/lib/gateway/gateway.ts#L109)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

just out of curiosity, why is it not part of the "usual response"?
you mean the txId is some kind of metadata, and the response is the real data?
</blockquote></details>

what I mean is, if the gateway and the playground respond with different things, it could be confusing for someone who is trying to build an app over starkex

**Comment by dan-ziv** [comment]
___
*[src/lib/gateway/gateway.ts, line 109 at r1](https://reviewable.io/reviews/starkware-industries/starkex-clientlib-js/10#-MocS6jj7bNVTrS_vxSf:-MocZinUC14da490isOO:bpouwzd) ([raw file](https://github.com/starkware-industries/starkex-clientlib-js/blob/f9b3bec7c6d230726e23493e687a4107d69dd7b2/src/lib/gateway/gateway.ts#L109)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

what I mean is, if the gateway and the playground respond with different things, it could be confusing for someone who is trying to build an app over starkex
</blockquote></details>

@dorimedini-starkware it will be the same response for all endpoints... this SDK isn't served only for the PG

**Comment by dan-ziv** [comment]
___
*[src/lib/gateway/gateway.ts, line 114 at r1](https://reviewable.io/reviews/starkware-industries/starkex-clientlib-js/10#-MocsFDtCIuekzLzyAeQ:-MomTMXT1aW3nJj5acp3:bpzub79) ([raw file](https://github.com/starkware-industries/starkex-clientlib-js/blob/f9b3bec7c6d230726e23493e687a4107d69dd7b2/src/lib/gateway/gateway.ts#L114)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

you don't want to include the txn id in the response in case of errors?
</blockquote></details>

Yes, we probably want. will add it

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-industries/starkex-clientlib-js/10)* status: all files reviewed, 1 unresolved discussion (waiting on @lior-stark)

___
*[src/lib/gateway/gateway.ts, line 109 at r1](https://reviewable.io/reviews/starkware-industries/starkex-clientlib-js/10#-MocS6jj7bNVTrS_vxSf:-MomV9kzC1tUm0h8hqH9:bb7x46g) ([raw file](https://github.com/starkware-industries/starkex-clientlib-js/blob/f9b3bec7c6d230726e23493e687a4107d69dd7b2/src/lib/gateway/gateway.ts#L109)):*
<details><summary><i>Previously, dan-ziv (Dan Ziv) wrote…</i></summary><blockquote>

@dorimedini-starkware it will be the same response for all endpoints... this SDK isn't served only for the PG
</blockquote></details>

ok cool

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-industries/starkex-clientlib-js/10)* status: all files reviewed, 1 unresolved discussion (waiting on @lior-stark)

**Review by lior-stark — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-industries/starkex-clientlib-js/10)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-ziv)

**Review by lior-stark — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-industries/starkex-clientlib-js/10#-:-MonYBS_0qCZhtB7qyGS:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-ziv)

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-industries/starkex-clientlib-js/10)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-ziv)

**Pull request merged**
